Handle empty TomDoc comment as empty, instead of throwing errors
    NoMethodError: undefined method `sub' for nil:NilClass
      .../tomdoc/lib/tomdoc/tomdoc.rb:130:in `tomdoc'